export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";

export const ADD_HOUSE = "ADD_HOUSE";
export const ADD_HOUSE_START = "ADD_HOUSE_START";
export const ADD_HOUSE_SUCCESS = "ADD_HOUSE_SUCCESS";
export const ADD_HOUSE_FAIL = "ADD_HOUSE_FAIL";

export const GET_FEATURED_HOUSES = "GET_FEATURED_HOUSES";
export const INITIATE_GET_FEATURED_HOUSES = "INITIATE_GET_FEATURED_HOUSES";
export const GET_FEATURED_HOUSES_FAILED = "GET_FEATURED_HOUSES_FAILED";

export const FETCH_SINGLE_HOUSE = "FETCH_SINGLE_HOUSE";
export const FETCH_SINGLE_HOUSE_START = "FETCH_SINGLE_HOUSE_START";
export const FETCH_SINGLE_HOUSE_SUCCESS = "FETCH_SINGLE_HOUSE_SUCCESS";
export const FETCH_SINGLE_HOUSE_FAIL = "FETCH_SINGLE_HOUSE_FAIL";

export const GET_HOUSE_INFOS = "GET_HOUSE_INFOS";
export const GET_HOUSE_INFOS_START = "GET_HOUSE_INFOS_START";
export const GET_HOUSE_INFOS_SUCCESS = "GET_HOUSE_INFOS_SUCCESS";
export const GET_HOUSE_INFOS_FAIL = "GET_HOUSE_INFOS_FAIL";

export const INITIATE_SEARCH_HOUSES = "INITIATE_SEARCH_HOUSES";
export const SEARCH_HOUSES = "SEARCH_HOUSES";
export const SEARCH_HOUSES_FAILED = "SEARCH_HOUSES_FAILED";
