
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';


export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_INITIATE_LOGOUT='AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_STATE='AUTH_CHECK_STATE';
export const AUTH_CHECK_TIMEOUT='AUTH_CHECK_TIMEOUT';

export const ADD_HOUSE='ADD_HOUSE';
export const ADD_HOUSE_START='ADD_HOUSE_START';
export const ADD_HOUSE_SUCCESS='ADD_HOUSE_SUCCESS';
export const ADD_HOUSE_FAIL='ADD_HOUSE_FAIL';

